name: svelte project CI/CD with Gradle

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: LogIn to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USER_ID }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}

    - name: Docker build & push to Docker repo
      run: |
        docker build -t ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest .
        docker push ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest

    - name: Deploy to Prod Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "./dist/*"
        target: "~/nginx-vol"
