name: svelte project CI/CD with Gradle

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: LogIn to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USER_ID }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}

    - name: Docker build & push to Docker repo
      run: |
        docker build -t ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest .
        docker push ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest

    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker-compose stop svelte
          sudo docker-compose rm -f svelte
          echo ${{ secrets.DOCKER_USER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER_ID }} --password-stdin
          sudo docker-compose pull ${{ secrets.DOCKER_USER_ID }}/${{ secrets.DOCKER_HUB_NAME }}:latest
          sudo docker-compose up -d --no-deps svelte
